### ISSUE TITLE
Implement channel quotas

### ISSUE THREAD

**Issue by rjw57** [uisautomation/media-webapp#331]
Each channel should have a quota associated with it before we enable channel creation. The basic idea is that any user can create a low-quota channel which is either a) part of no institution or b) "sponsored" by a special "free tier" institution. For a channel's quota to be increased, it needs to be "adopted" by an institution and then the institutional administrator can increase the quota as appropriate.

A user should have a maximum number of "free-tier" channels they can create. This issue tracks the progress of this feature.

* [ ] Decide what quota types we want (maximum number of media items, perhaps?)
* [ ] Add per-channel quotas and default values for them. Ideally, these defaults should be taken from the database so they can be changed easily in future without modifying the code. This requires some design work.
* [ ] Create the concept of an "institutional administrator". Perhaps we want to add an "Institution" model with an "admin permission"? This requires some design work.
* [ ] Expose an API for editing quotas on channels available to institutional administrators.
* [ ] Record the user which created a channel.
* [ ] Do not allow a user with the maximum number of "free-tier" channels to create more channels. Ideally, this policy should be in the database somehow. This requires some design work.
