### ISSUE TITLE
Clean up the list of issues and create a new milestone to deploy Media Platform Beta

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/media-webapp#423]
- [ ] Clean up all the issues list
- [ ] Write up all the remaining user stories that we need to develop to stop SMS and deploy Media Platform Beta
- [ ] Create a new milestone with the list of all tasks to get us to Media Platform Beta
